---
- name: Get Java - 1
  raw: wget https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.2%2B7/OpenJDK15U-jdk_x64_linux_hotspot_15.0.2_7.tar.gz

- name: Get Java - 2
  raw: tar xvfz OpenJDK15U-jdk_x64_linux_hotspot_15.0.2_7.tar.gz

- name: Install java
  raw: sudo mv ./jdk-15.0.2+7 /opt/

- name: Install jq
  apt:
    name: jq
    state: present
